const glow=document.querySelector('.cursor-glow');
let audioOn=false, audioCtx;
window.addEventListener('pointermove',e=>{glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px';document.querySelectorAll('.hero-art .float-chip').forEach((el,i)=>{el.style.transform=`translate(${(e.clientX-innerWidth/2)*(.012+i*.004)}px,${(e.clientY-innerHeight/2)*(.012+i*.004)}px)`})});
function ping(freq=420){if(!audioOn)return;if(!audioCtx)audioCtx=new AudioContext();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.0001,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.035,audioCtx.currentTime+.015);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.12);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.13)}
document.querySelectorAll('a,button').forEach((el,i)=>el.addEventListener('mouseenter',()=>ping(300+i*18)));
const sound=document.getElementById('soundToggle');sound.addEventListener('click',()=>{audioOn=!audioOn;sound.innerHTML=audioOn?'◉ <span>صوت: ON</span>':'◉ <span>صوت</span>';if(audioOn)ping(620)});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
document.getElementById('langToggle').addEventListener('click',e=>{const on=document.documentElement.lang==='ar';document.documentElement.lang=on?'en':'ar';document.documentElement.dir=on?'ltr':'rtl';e.target.textContent=on?'AR':'EN';document.body.classList.toggle('english',on);alert(on?'English interface is available for navigation.':'تمت استعادة الواجهة العربية.');});
const contactForm=document.querySelector('.contact-form');const formStatus=contactForm?.querySelector('.form-status');contactForm?.addEventListener('submit',e=>{if(!contactForm.checkValidity()){e.preventDefault();contactForm.reportValidity();return}ping(700);if(formStatus)formStatus.textContent='جارٍ إرسال رسالتك…';contactForm.querySelector('button[type=submit]').disabled=true;});if(location.search.includes('sent=1')&&formStatus){formStatus.textContent='تم إرسال رسالتك بنجاح، شكراً لتواصلك.';history.replaceState({},document.title,location.pathname+'#contact');}
const workTabs=document.querySelectorAll('.work-tab');const groups=document.querySelectorAll('.media-group');workTabs.forEach(tab=>tab.addEventListener('click',()=>{workTabs.forEach(t=>t.classList.remove('active'));tab.classList.add('active');groups.forEach(g=>g.style.display=g.dataset.group===tab.dataset.filter?'grid':'none');ping(520)}));
(function initThree(){if(!window.THREE)return;const canvas=document.getElementById('three-bg'),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(60,innerWidth/innerHeight,.1,1000);camera.position.z=8;const mobile=matchMedia('(max-width: 700px)').matches;const renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:!mobile});renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1.25:1.75));renderer.setSize(innerWidth,innerHeight);const group=new THREE.Group();scene.add(group);const material=new THREE.PointsMaterial({color:0x57b994,size:.045,transparent:true,opacity:.75});const geo=new THREE.BufferGeometry(),count=mobile?260:700,positions=new Float32Array(count*3);for(let i=0;i<count*3;i+=3){positions[i]=(Math.random()-.5)*16;positions[i+1]=(Math.random()-.5)*10;positions[i+2]=(Math.random()-.5)*8}geo.setAttribute('position',new THREE.BufferAttribute(positions,3));group.add(new THREE.Points(geo,material));const torus=new THREE.Mesh(new THREE.TorusGeometry(3.7,.008,8,180),new THREE.MeshBasicMaterial({color:0x8bd9bd,transparent:true,opacity:.35}));torus.rotation.x=1.1;group.add(torus);const torus2=torus.clone();torus2.scale.set(.7,.7,.7);torus2.rotation.y=.8;torus2.material=torus.material.clone();torus2.material.color.set(0x9bcfe0);group.add(torus2);let mx=0,my=0;window.addEventListener('pointermove',e=>{mx=(e.clientX/innerWidth-.5)*.5;my=(e.clientY/innerHeight-.5)*.3});let pageVisible=true;document.addEventListener('visibilitychange',()=>pageVisible=document.visibilityState==='visible');function animate(){requestAnimationFrame(animate);if(!pageVisible)return;group.rotation.y+=(mx-group.rotation.y)*.012;group.rotation.x+=(my-group.rotation.x)*.012;torus.rotation.z+=.0018;torus2.rotation.z-=.001;renderer.render(scene,camera)}animate();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)})})();
const themeToggle=document.getElementById('themeToggle');const savedTheme=localStorage.getItem('tamer-theme');if(savedTheme==='dark')document.body.classList.add('dark');function syncTheme(){const dark=document.body.classList.contains('dark');themeToggle.innerHTML=dark?'☀ <span>فاتح</span>':'☾ <span>الوضع</span>';themeToggle.setAttribute('aria-label',dark?'تفعيل الوضع الفاتح':'تفعيل الوضع المظلم')}syncTheme();themeToggle.addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem('tamer-theme',document.body.classList.contains('dark')?'dark':'light');syncTheme();ping(580)});
groups.forEach((g,i)=>{g.hidden=i!==0});workTabs.forEach(tab=>tab.addEventListener('click',()=>groups.forEach(g=>{g.hidden=g.dataset.group!==tab.dataset.filter}))); 
